blog/urls.py
from django.urls import path
from . import views

app_name = "blog"

urlpatterns = [
    path('',views.blog_title,name='blog_title'),  #name是别名
    path('<int:article_id>/',views.blog_article,name='blog_article'), #views.blog_article也可以加上"",用"views.blog_article"显示
]

course/urls.py
from django.urls import path
from django.views.generic import TemplateView
from .views import CourseListView,ManageCourseListView,CreateCourseView,DeleteCourseView,CreateLessonView,ListLessonView,DetailLessonView,StudentListLessonView,UpdateCourseView


app_name = "course"

urlpatterns = [
    path('about/',TemplateView.as_view(template_name="course/about.html"),name="about"), #关于本站
    path('course-list/',CourseListView.as_view(),name="course_list"), #课程列表
    path('manage-course/',ManageCourseListView.as_view(),name="manage_course"),
    path('create-course/',CreateCourseView.as_view(),name="create_course"),
    path('update-course/<int:pk>/',UpdateCourseView.as_view(),name="update_course"),
    path('delete-course/<int:pk>/',DeleteCourseView.as_view(),name="delete_course"),
    path('create-lesson/',CreateLessonView.as_view(),name="create_lesson"),
    path('list-lessons/<int:course_id>/',ListLessonView.as_view(),name="list_lessons"),
    path('detail-lessons/<int:lesson_id>/',DetailLessonView.as_view(),name="detail_lesson"),
    path('lessons-list/<int:course_id>/',StudentListLessonView.as_view(),name="lessons_list"),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('blog/',include('blog.urls','blog'),namespace='blog'),
    path('blog/',include('blog.urls',namespace='blog')),
    path('account/',include('account.urls',namespace = 'account')),
    path('article/',include('article.urls',namespace = 'article')),
    path('home/', TemplateView.as_view(template_name="home.html"), name='home'), # 这里设置name，为了在模板文件中，写name就能找到这个路由，name参数相当于别名
    path('image/',include('image.urls',namespace = 'image')),
    path('course/',include('course.urls',namespace='course')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

course/models.py
from django.db import models
from django.contrib.auth.models import User
from slugify import slugify
from .fields import OrderField

# Create your models here.


#课程数据模型
class Course(models.Model):
    user = models.ForeignKey(User,on_delete = models.CASCADE,related_name = "courses_user")
    title = models.CharField(max_length = 200)
    slug = models.SlugField(max_length = 200,unique = True)
    overview = models.TextField()
    created = models.DateTimeField(auto_now_add = True)
    student = models.ManyToManyField(User,related_name = "courses_joined",blank = True)

    class Meta:
        ordering = ('-created',)

    def save(self, *args,**kwargs):
        self.slug = slugify(self.title)
        super(Course,self).save(*args,**kwargs)

    def __str__(self):
        return self.title


def user_directory_path(instance,filename):
    return "courses/user_{0}/{1}".format(instance.user.id,filename)


#课程内容的数据模型
class Lesson(models.Model):
    user = models.ForeignKey(User,on_delete = models.CASCADE,related_name = "lesson_user")
    course = models.ForeignKey(Course,on_delete = models.CASCADE,related_name = "lesson")
    title = models.CharField(max_length = 200)
    video = models.FileField(upload_to = user_directory_path) #用于接收上传的视频
    description = models.TextField(blank = True)
    attach = models.FileField(blank = True,upload_to = user_directory_path) #用于接收上传的附件
    created = models.DateTimeField(auto_now_add = True)
    order = OrderField(blank = True,for_fields = ['course'])  #order用来存储某内容在相应的课程标题Course中的序号，默认序号从0开始

    class Meta:
        ordering = ['order']

    def __str__(self):
        return '{}.{}'.format(self.order,self.title)

course/forms.py
from django import forms
from .models import Course,Lesson


#创建课程表单
class CreateCourseForm(forms.ModelForm):
    class Meta:
        model = Course
        fields =("title","overview")


#课程内容表单
class CreateLessonForm(forms.ModelForm):
    class Meta:
        model = Lesson
        fields = ['course','title','video','description','attach']

    def __init__(self,user,*args,**kwargs):
        super(CreateLessonForm,self).__init__(*args,**kwargs)
        self.fields['course'].queryset = Course.objects.filter(user=user)

course/views.py
from django.shortcuts import render,redirect
from django.views.generic import TemplateView,ListView
from django.views.generic.edit import CreateView,DeleteView,UpdateView
from .models import Course,Lesson
from braces.views import LoginRequiredMixin
from .forms import CreateCourseForm,CreateLessonForm
from django.urls import reverse_lazy
from django.http import HttpResponse
import json
from django.views import View
from django.shortcuts import get_object_or_404
from django.views.generic.base import TemplateResponseMixin


# Create your views here.

#课程列表视图
class CourseListView(ListView):
    model = Course #获取Course中的所有数据
    context_object_name = "courses" #声明传入模板course_list.html中的变量名称
    template_name = 'course/course_list.html' #指定模板


class UserMixin:
    def get_queryset(self):
        qs = super(UserMixin, self).get_queryset()
        return qs.filter(user=self.request.user)


class UserCourseMixin(UserMixin,LoginRequiredMixin):
    model = Course
    login_url = "/account/login" #当用户没有登录的时候，强制跳转到登录页面


class ManageCourseListView(UserCourseMixin, ListView):
    context_object_name = "courses"  #此处的courses返回的是request.user名下创建的courses，原因是通过继续UserMinxin的return实现
    template_name = 'course/manage/manage_course_list.html'


#新增课程的方法
class CreateCourseView(UserCourseMixin,CreateView):
    fields = ['title','overview'] #声明在表单中显示的字段
    template_name = 'course/manage/create_course.html'  #指定前端展示的html模板

    def post(self, request, *args, **kwargs):
        form = CreateCourseForm(data = request.POST)
        if form.is_valid():
            new_course = form.save(commit = False)
            new_course.user = self.request.user
            new_course.save()
            return redirect("course:manage_course") #当表单数据保存以后，重新跳转到指定页面
        return self.render_to_response({"form":form})


#编辑课程的方法
class UpdateCourseView(UserCourseMixin,UpdateView):
    fields = ['title','overview'] #声明在表单中显示的字段
    template_name = 'course/manage/update_course.html'  #指定前端展示的html模板
    success_url = reverse_lazy("course:manage_course")  #提交后调整页面


#删除课程的方法
class DeleteCourseView(UserCourseMixin, DeleteView):
    #template_name = 'course/manage/delete_course_confirm.html'
    success_url = reverse_lazy("course:manage_course") #删除成功，跳转的页面

    def dispatch(self, *args, **kwargs):
        resp = super(DeleteCourseView, self).dispatch(*args, **kwargs)
        if self.request.is_ajax():
            response_data = {"result": "ok"}
            return HttpResponse(json.dumps(response_data), content_type="application/json")
        else:
            return resp


#课程内容的视图方法
class CreateLessonView(LoginRequiredMixin,View):
    model = Lesson
    login_url = "/account/login/"

    def get(self,request,*args,**kwargs):
        form = CreateLessonForm(user = self.request.user) #创建表单类实例
        return render(request,"course/manage/create_lesson.html",{"form":form})

    def post(self,request,*args,**kwargs):
        form = CreateLessonForm(self.request.user,request.POST,request.FILES)
        if form.is_valid():
            new_lesson = form.save(commit = False)
            new_lesson.user = self.request.user
            new_lesson.save()
            return redirect("course:manage_course")


#课程内容标题列表视图
class ListLessonView(LoginRequiredMixin,TemplateResponseMixin,View):
    login_url = "/account/login/"
    template_name = 'course/manage/list_lessons.html'

    def get( self,request,course_id ):
        course = get_object_or_404(Course,id=course_id)
        return self.render_to_response({'course':course})


#课程内容详情视图
class DetailLessonView(LoginRequiredMixin,TemplateResponseMixin,View):
    login_url = "/account/login/"
    template_name = "course/manage/detail_lesson.html"

    def get( self,request,lesson_id ):
        lesson = get_object_or_404(Lesson,id=lesson_id)
        return self.render_to_response({"lesson":lesson})


class StudentListLessonView(ListLessonView):
    template_name = "course/slist_lessons.html"  #指定前端展示的模板html

    def post(self , request , *args , **kwargs):
        course = Course.objects.get(id = kwargs['course_id'])
        course.student.add(self.request.user)
        return HttpResponse("ok")

templates/course/about.html
{% extends "base.html" %}
{% block title %}About itdiffer.com{% endblock %}
{% block content %}
<div class="container">
    <h1 class="text-center">Welcome XXXXX.com</h1>
    <p class="text-center">深圳是中国改革开放的窗口。时间就是金钱，自强不息，奋斗不止。</p>
    <p class="text-center">QQ号：460357327</p>
    <h2 class="text-center">欢迎访问</h2>
</div>
{% endblock %}

templates/course/course_list.html
{% extends "base.html" %}
{% block title %}Course List{% endblock %}
{% block content %}
<div class="container">
    <table class="table table-hover">
        <tr>
            <td>序号</td>
            <td>课程标题</td>
            <td>讲师</td>
            <td>发布日期</td>
        </tr>
        {% for course in courses %}
        <!-- courses变量名在CourseListView视图中定义的context_object_name指出       -->
        <tr id="{{ forloop.counter }}">
            <td>{{ forloop.counter }}</td>
            <td><a href="{% url 'course:lessons_list' course.id %}">{{ course.title }}</a></td>
            <td>{{ course.user.username }}</td>
            <td>{{ course.created }}</td>
        </tr>
        {% endfor %}
    </table>
</div>
{% endblock %}

templates/course/slist_lessons.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}Lessons List{% endblock %}
{% block content %}
<div class="container">
    <div class='text-center'>
        <h1>{{ course.title }}</h1>
        <p>课程内容列表</p>
        <form action="." method="post" class="form-horizontal">{% csrf_token %}
            <input type="button" onclick="start_learn({{course.id}})" value="Try my best to learn the course">
        </form>
    </div>
    <table class="table table-hover" style="margin-top:10px">
        <tr>
            <td>序号</td>
            <td>内容标题</td>
            <td>概要</td>
            <td>发布日期</td>
        </tr>
        {% for lesson in course.lesson.all %}
        <tr id={{ forloop.counter }}>
            <td>{{ forloop.counter }}</td>
            <td><a href="{% url 'course:detail_lesson' lesson.id %}">{{ lesson.title }}</a></td>
            <td>{{ lesson.description | slice:'70'|linebreaks }}</td>
            <td>{{ lesson.created|date:"Y-m-d" }}</td>
        </tr>
        {% empty %}
        <p>还没有发布具体内容，请等待。</p>
        {% endfor %}
    </table>
</div>

<script src='{% static "js/jquery.js" %}'></script>
<script src='{% static "js/csrf.js" %}'></script>
<script>
function start_learn(course_id){
    $.ajaxSetup({
        beforeSend: function(xhr, settings) {
            function getCookie(name) {
                var cookieValue = null;
                if (document.cookie && document.cookie != '') {
                    var cookies = document.cookie.split(';');
                    for (var i = 0; i < cookies.length; i++) {
                        var cookie = jQuery.trim(cookies[i]);
                        if (cookie.substring(0, name.length + 1) == (name + '=')) {
                            cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                            break;
                        }
                    }
                }
                return cookieValue;
            }
            if (!(/^http:.*/.test(settings.url) || /^https:.*/.test(settings.url))) {
                xhr.setRequestHeader("X-CSRFToken", getCookie('csrftoken'));
            }
        }
    });

    $.ajax({
        type: "POST",
        url: "{% url 'course:lessons_list' course.id %}",
        data: {'course_id':course_id},
        success:function(e){
            if(e=="ok"){
                alert("You have enroll this course.")
            }else{
                alert("Sorry, There are some mistakes.")
            }
        },
    });
}
</script>
{% endblock %}