article/urls.py
from django.urls import path,re_path
from . import views,list_views


app_name = "article"

urlpatterns = [
    path('article-column/',views.article_column,name="article_column"),  # 这里设置name，为了在模板文件中，写name就能找到这个路由
    path('rename-column/', views.rename_article_column, name="rename_article_column"), #编辑文章
    path('del-column/',views.del_article_column,name="del_article_column"), #删除文章
    path('article-post/',views.article_post,name="article_post"), #发布文章
    path('article-list/',views.article_list,name="article_list"), #文章列表
    re_path('article-detail/(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.article_detail, name="article_detail"), #文章详情
    path('del-article/',views.del_article,name="del_article"),
    path('redit-article/<int:article_id>/',views.redit_article,name="redit_article"),
    path('list-article-titles/',list_views.article_titles,name="article_titles"),
    path('article-content/<int:id>/<slug:slug>/',list_views.article_detail,name="article_content"), #此处也是显示文章详情，对应不同的html模板
    path('list-article-titles/<username>/',list_views.article_titles,name="author_articles"),
    path('like-article/',list_views.like_article,name="like_article"),
    path('article-tag/',views.article_tag,name="article_tag"),
    path('del-article-tag/',views.del_article_tag,name="del_article_tag"),
]

blog/urls.py
from django.urls import path
from . import views

app_name = "blog"

urlpatterns = [
    path('',views.blog_title,name='blog_title'),  #name是别名
    path('<int:article_id>/',views.blog_article,name='blog_article'), #views.blog_article也可以加上"",用"views.blog_article"显示
]

mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('blog/',include('blog.urls','blog'),namespace='blog'),
    path('blog/',include('blog.urls',namespace='blog')),
    path('account/',include('account.urls',namespace = 'account')),
    path('article/',include('article.urls',namespace = 'article')),
    path('home/', TemplateView.as_view(template_name="home.html"), name='home'), # 这里设置name，为了在模板文件中，写name就能找到这个路由，name参数相当于别名
    path('image/',include('image.urls',namespace = 'image')),
    path('course/',include('course.urls',namespace='course')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

article/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone #1
from django.urls import reverse
from slugify import slugify


# Create your models here.


#文章栏目数据模型
class ArticleColumn(models.Model):
    user = models.ForeignKey(User,on_delete = models.CASCADE,related_name = 'article_column')
    column = models.CharField(max_length = 200)
    created = models.DateField(auto_now_add = True)

    def __str__(self):
        return self.column


#文章标签数据模型
class ArticleTag(models.Model):
    author = models.ForeignKey(User,on_delete = models.CASCADE,related_name = "tag")
    tag = models.CharField(max_length = 500)
    def __str__(self):
        return self.tag


#文章数据模型
class ArticlePost(models.Model):
    author = models.ForeignKey(User, on_delete = models.CASCADE, related_name = "article") #文章作者，文章与作者属于一对多的关系
    title = models.CharField( max_length = 200) #文章标题
    slug = models.SlugField(max_length = 500) #用于将文章标题转化为英文跟-
    column = models.ForeignKey(ArticleColumn , on_delete = models.CASCADE, related_name = "article_column") #文章栏目，文章栏目与文章属于一对多的关系
    body = models.TextField() #文章内容
    created = models.DateTimeField(default = timezone.now) #文章创建时间
    updated = models.DateTimeField(auto_now = True) #文章更新时间
    user_like = models.ManyToManyField(User,related_name = "article_like",blank = True)
    # article_tag = models.ManyToManyField(ArticleTag,related_name = "article_tag",blank = True)
    article_tag = models.ManyToManyField(ArticleTag,related_name = 'article_tag',blank = True)

    class Meta:
        ordering = ("-updated",) #按照更新时间updated字段进行降序排序，最新的放在最前面
        # ordering = ("updated" ,)  # 按照更新时间updated字段进行升序排序，最久的放在最前面
        index_together = (('id', 'slug'),) #对数据库中这2个字段建立索引

    def __str__( self ):
        return self.title  #__str__方法返回一个字符串，当做这个对象的描写

    #对默认的save方法进行重写
    def save(self, *args, **kargs):
        self.slug = slugify(self.title)
        super(ArticlePost , self).save(*args, **kargs)

    def get_absolute_url( self ):
        return reverse("article:article_detail", args = [self.id , self.slug])  #得到相应文章的路径

    def get_url_path( self ):
        return reverse("article:article_content", args = [self.id , self.slug]) #得到相应文章的路径


#评论功能数据模型
class Comment(models.Model):
    article = models.ForeignKey(ArticlePost,on_delete = models.CASCADE,related_name = "comments") #将本数据模型与ArticlePost数据模型建立多对一的关系，即一篇文章可以有多条评论
    commentator = models.CharField(max_length = 90)
    body = models.TextField()
    created = models.DateTimeField(auto_now_add = True)

    class Meta:
        ordering = ('-created',) #按照created的倒序排序

    def __str__(self):
        return "Comment by {0} on {1}".format(self.commentator.username,self.article)

article/forms.py
from django import forms
from .models import ArticleColumn,ArticlePost,Comment,ArticleTag


#栏目表单类
class ArticleColumnForm(forms.ModelForm):
    class Meta:
        model = ArticleColumn
        fields = ("column",)


#文章表单类
class ArticlePostForm(forms.ModelForm):
    class Meta:
        model = ArticlePost
        fields = ("title","body") #将ArticlePost表中的字段拿出来，需要什么字段拿什么字段，这里列出来只需要拿title,body2个字段


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment  #指定数据源
        fields = ("commentator","body",)


#文章标签表单类
class ArticleTagForm(forms.ModelForm):
    class Meta:
        model = ArticleTag
        fields = ('tag',)

article/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from .models import ArticleColumn,ArticlePost,ArticleTag
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponse
from .forms import ArticleColumnForm,ArticlePostForm,ArticleTagForm
from django.views.decorators.http import require_POST
from django.shortcuts import get_object_or_404
from django.core.paginator import Paginator,EmptyPage,PageNotAnInteger
import json

# Create your views here.


#新增栏目的视图
@login_required(login_url = '/account/login')
@csrf_exempt #解决提交表单中遇到的CSRF问题的一种方式
def article_column(request):
    # columns = ArticleColumn.objects.filter(user=request.user)
    # return render(request,"article/column/article_column.html",{"columns":columns}
    if request.method == "GET":
        columns_list = ArticleColumn.objects.filter(user=request.user)
        column_from = ArticleColumnForm()
        #下面是分页方法
        paginator = Paginator(columns_list,10)
        page = request.GET.get('page')
        try:
            current_page = paginator.page(page)
            columns = current_page.object_list
        except PageNotAnInteger:
            current_page = paginator.page(1)
            columns = current_page.object_list
        except EmptyPage:
            current_page = paginator.page(paginator.num_pages)
            columns = current_page.object_list

        return render(request,"article/column/article_column.html",{"columns":columns,"column_form":column_from,"page": current_page})  #传入2个参数columns跟column_form到article_column.html模板中
    if request.method == "POST":
        column_name = request.POST['column']
        columns = ArticleColumn.objects.filter(user_id=request.user.id,column=column_name) #7传入当前用户跟栏目名称2个参数后，来查询当前用户是否已经创建过当前的栏目名称，如果没有创建该栏目则允许创建提交，否则创建失败
        if columns:
            return HttpResponse('2')
        else:
            ArticleColumn.objects.create(user=request.user,column=column_name) #create()函数直接让数据插入数据库
            return HttpResponse('1')


#编辑栏目的视图
@login_required(login_url = '/account/login')
@require_POST  #目的是保证此视图函数只接受通过POST方法提交的数据
@csrf_exempt
def rename_article_column(request):
    column_name = request.POST["column_name"]
    column_id = request.POST['column_id']
    try:
        line = ArticleColumn.objects.get(id=column_id) #根据所要修改的栏目名称所在记录的id，查询到该数据，并建立实例对象
        line.column = column_name #重新赋值
        line.save() #将数据保存到数据库
        return HttpResponse("1")
    except:
        return HttpResponse("0")


#删除栏目的视图
@login_required(login_url = '/account/login')
@require_POST
@csrf_exempt
def del_article_column(request):
    column_id = request.POST["column_id"] #获取Ajax传过来的column_id
    try:
        line = ArticleColumn.objects.get(id=column_id)
        line.delete() # 删除该记录
        return HttpResponse("1")
    except:
        return HttpResponse("2")


#文章视图函数
@login_required(login_url='/account/login')
@csrf_exempt
def article_post(request):
    if request.method == "POST": #以POST方式提交数据
        article_post_form = ArticlePostForm(data=request.POST)
        if article_post_form.is_valid(): #检查表单数据是否检验通过
            cd = article_post_form.cleaned_data
            try:
                new_article = article_post_form.save(commit=False) #先不提交到数据库
                new_article.author = request.user
                new_article.column = request.user.article_column.get(id=request.POST['column_id'])
                new_article.save()
                tags = request.POST['tags']
                if tags:
                    for atag in json.loads(tags):
                        tag = request.user.tag.get(tag=atag)
                        new_article.article_tag.add(tag)
                return HttpResponse("1")
            except:
                return HttpResponse("2")
        else:
            return HttpResponse("3")
    else: #GET方式
        article_post_form = ArticlePostForm()
        article_columns = request.user.article_column.all() #获取当前用户的所有栏目
        article_tags = request.user.tag.all()#获取当前用户的所有文章标签
        return render(request, "article/column/article_post.html",{"article_post_form":article_post_form, "article_columns":article_columns, "article_tags":article_tags})


#文章标题列表视图
@login_required(login_url = '/account/login')
def article_list(request):
    articles_list = ArticlePost.objects.filter(author = request.user) #通过author属性，可以查询对应作者所创建的所有文章
    paginator = Paginator(articles_list, 10)
    page = request.GET.get('page')
    try :
        current_page = paginator.page(page)
        articles = current_page.object_list
    except PageNotAnInteger :
        current_page = paginator.page(1)
        articles = current_page.object_list
    except EmptyPage :
        current_page = paginator.page(paginator.num_pages)
        articles = current_page.object_list
    return render(request , "article/column/article_list.html", {"articles": articles, "page": current_page})


#文章详情视图
@login_required(login_url = '/account/login')
def article_detail(request,id,slug):
    article=get_object_or_404(ArticlePost,id=id,slug=slug)
    return render(request,"article/column/article_detail.html",{"article":article})


#删除文章视图
@login_required(login_url = '/account/login')
@require_POST
@csrf_exempt
def del_article(request):
    article_id = request.POST['article_id']
    try:
        article = ArticlePost.objects.get(id=article_id)
        article.delete()
        return HttpResponse("1")
    except:
        return HttpResponse("2")


#编辑文章视图
@login_required(login_url = '/account/login')
@csrf_exempt
def redit_article(request,article_id):
    if request.method == 'GET':
        article_columns = request.user.article_column.all()
        article = ArticlePost.objects.get(id=article_id)
        this_article_form = ArticlePostForm(initial = {"title":article.title})
        this_article_column = article.column
        return render(request,"article/column/redit_article.html",
                      {"article":article,
                       "article_columns":article_columns,
                       "this_article_column":this_article_column,
                       "this_article_form":this_article_form})
    else:
        redit_article = ArticlePost.objects.get(id=article_id)
        try:
            redit_article.column = request.user.article_column.get(id=request.POST['column_id'])
            redit_article.title = request.POST['title']
            redit_article.body = request.POST['body']
            redit_article.save()
            return HttpResponse("1")
        except:
            return HttpResponse("2")


@login_required ( login_url = '/account/login' )
@csrf_exempt
def article_tag( request ) :
    if request.method == "GET" :
        article_tags = ArticleTag.objects.filter ( author = request.user )
        article_tag_form = ArticleTagForm ()
        return render ( request , "article/tag/tag_list.html" ,
                        {"article_tags" : article_tags , "article_tag_form" : article_tag_form} )

    if request.method == "POST" :
        tag_post_form = ArticleTagForm ( data = request.POST )
        if tag_post_form.is_valid () :
            try :
                new_tag = tag_post_form.save ( commit = False )
                new_tag.author = request.user
                new_tag.save ()
                return HttpResponse ( "1" )
            except :
                return HttpResponse ( "the data cannot be save." )
        else :
            return HttpResponse ( "sorry, the form is not valid." )


@login_required(login_url = '/account/login')
@require_POST
@csrf_exempt
def del_article_tag(request):
    tag_id = request.POST['tag_id']
    try:
        tag = ArticleTag.objects.get(id = tag_id)
        tag.delete()
        return HttpResponse("1")
    except:
        return HttpResponse("2")

templates/article/column/article_column.html
{% extends "article/base.html" %}
{% load staticfiles %}
{% block title %}article column{% endblock %}
{% block content %}
<div>
    <p class="text-right"><!--button class="btn btn-primary">add column</button-->
        <button id= "add_column" onclick="add_column()" class="btn btn-primary"> 新增栏目</button>
    </p>
    <table class="table table-hover">
        <tr>
            <td>序号</td>
            <td>栏目名称</td>
            <td>操作</td>
        </tr>
        <!--获取当前登录用户创建的所有栏目信息，通过for循环遍历，在前端展示-->
        {% for column in columns %}
        <tr>
            <td>{{ forloop.counter }}</td>
            <td>{{ column.column }}</td>
            <td>
                <a name="edit" href="javascript:;" onclick="edit_column(this, {{ column.id }})">
                    <span class="glyphicon glyphicon-pencil"></span>
                </a>
                <!-- this指当前标签元素-->
                <a name="delete" href="javascript:;" onclick="del_column(this, {{ column.id }})">
                    <span class="glyphicon glyphicon-trash" style="margin-left:20px;"></span>
                </a>
            </td>
        </tr>
        {% empty %}
        <p>还没有设置栏目，太懒了。</p>
        {% endfor %}
    </table>
    {% include "paginator.html" %}
</div>

<script type="text/javascript" src='{% static "js/jquery.js" %}'></script>
<script type="text/javascript" src="{% static 'js/layer.js'%}"></script>
<script type="text/javascript">
    function add_column() {
        var index = layer.open({
            type: 1,
            skin: "layui-layer-rim",
            area: ["400px", "200px"],
            title: "新增栏目",
            content: '<div class="text-center" style="margin-top:20px">\
                <p> 请输入新的栏目名称</p>\
                    <p>{{ column_form.column }}</p>\
</div >',
            btn: ['确定', '取消'],
            yes: function (index, layero) {
                column_name = $('#id_column').val();
                $.ajax({
                    url: '{% url "article:article_column" %}',
                    type: 'POST',
                    data: { "column": column_name },
                    success: function (e) {
                        if (e == "1") {
                            parent.location.reload();
                            layer.msg("提交成功");
                        } else {
                            layer.msg("此栏目已有，请更换名称")
                        }
                    },
                });
            },
            btn2: function (index, layero) {
                layer.close(index);
            }
        });
    }

    function edit_column(the, column_id){
        var name = $(the).parents("tr").children("td").eq(1).text();
        var index = layer.open({
            type: 1,
            skin: "layui-layer-rim",
            area: ["400px", "200px"],
            title: "编辑栏目",
            content: '<div class="text-center" style="margin-top:20px"> <p>需编辑的栏目名称</p><p><input type="text" id="new_name" value="'+name+'"></p></div>',
            btn:['确定', '取消'],
            yes: function(index, layero){
                new_name = $("#new_name").val();
                $.ajax({
                    url: "{% url 'article:rename_article_column' %}",
                    type: "POST",
                    data: {"column_id": column_id, "column_name": new_name},
                    success: function(e){
                        if(e=="1"){
                            parent.location.reload();
                            layer.msg("提交成功");
                        }else{
                            layer.msg("新的名称没有保存,修改失败。")
                        }
                    },
                });
            },
        });
    }

    function del_column(the, column_id){
        var name = $(the).parents("tr").children("td").eq(1).text();
        layer.open({
            type: 1,
            skin: "layui-layer-rim",
            area: ["400px", "200px"],
            title: "删除栏目",
            content: '<div class="text-center" style="margin-top:20px"><p>是否确定删除{'+name+'}栏目</p> </div>',
            btn:['确定', '取消'], yes: function(){
                $.ajax({
                    url: '{% url "article:del_article_column" %}',
                    type:"POST",
                    data: {"column_id":column_id},
                    success: function(e){
                        if(e=="1"){
                            parent.location.reload();
                            layer.msg("删除成功");
                        }else{
                            layer.msg("删除失败");
                        }
                    },
                })
            },
        });
    }
</script>
{% endblock %}

templates/article/column/article_detail.html
{% extends "article/base.html" %}
{% load staticfiles %}
{% block title %}articles list{% endblock %}
{% block content %}
<div>
    <header>
        <h1>{{ article.title }}</h1>
        <p>作者：{{ user.username }}</p>
    </header>

    <link rel="stylesheet" href="{% static 'editor/css/editormd.preview.css' %}" />
    <div id='editormd-view'>
        <textarea id="append-test" style="display:none;">
{{ article.body }}
        </textarea>
    </div>
</div>
<script src='{% static "js/jquery.js" %}'></script>
<script src='{% static "editor/lib/marked.min.js" %}'></script>
<script src='{% static "editor/lib/prettify.min.js" %}'></script>
<script src='{% static "editor/lib/raphael.min.js" %}'></script>
<script src='{% static "editor/lib/underscore.min.js" %}'></script>
<script src='{% static "editor/lib/sequence-diagram.min.js" %}'></script>
<script src='{% static "editor/lib/flowchart.min.js" %}''></script>
<script src='{% static "editor/lib/jquery.flowchart.min.js" %}'></script>
<script src='{% static "editor/editormd.js" %}'></script>
<script type="text/javascript">
$(function(){
    editormd.markdownToHTML("editormd-view", {
        htmlDecode: "style, script, iframe",
        emoji: true,
        taskList:true,
        tex:true, //默认不解析
        flowChart:true, //默认不解析
        sequenceDiagram : true, //默认不解析
    });
});
</script>
{% endblock %}

templates/article/column/article_list.html
{% extends "article/base.html" %}
{% load staticfiles %}
{% block title %}articles list{%endblock%}
{% block content %}
<div>
     <div class='text-right'>
        <a href="{% url 'article:article_post' %}">
            <button type="button" class="btn btn-primary">新增文章</button>
        </a>
    </div>

    <table class="table table-hover" style="margin-top:10px">
        <tr>
            <td>序号</td>
            <td>标题</td>
            <td>栏目</td>
            <td>操作</td>
        </tr>
    {% for article in articles %}
    <tr id={{ article.id }}>
        <td>{{ forloop.counter }}</td>
        <td><a href="{{article.get_absolute_url}}">{{ article.title }}</a></td>
        <td>{{ article.column }}</td>
        <td><a name="edit" href="{% url 'article:redit_article' article.id %}"><span class="glyphicon glyphicon-pencil"></span></a>
            <a name="delete" href="javascript:;" onclick="del_article(this,{{ article.id }})"><span class="glyphicon glyphicon-trash" style="margin-left:20px; "></span></a>
        </td>
    </tr>
    {% endfor %}
    </table>
    {% include "paginator.html" %}
</div>

<script type="text/javascript" src='{% static "js/jquery.js" %}'></script>
<script type="text/javascript" src="{% static 'js/layer.js'%}"></script>
<script type="text/javascript">
    function del_article(the, article_id){
        var article_name = $(the).parents("tr").children("td").eq(1).text();
        layer.open({
            type: 1,
            skin: "layui-layer-rim",
            area: ["400px", "200px"],
            title: "删除文章",
            content: '<div class="text-center" style="margin-top:20px"><p>是否确定删除《'+article_name+'》</p> </div>',
            btn:['确定', '取消'], yes: function(){
                $.ajax({
                    url: '{% url "article:del_article" %}',
                    type:"POST",
                    data: {"article_id":article_id},
                    success: function(e){
                        if(e=="1"){
                            parent.location.reload();
                            layer.msg("has been deleted.");
                        }else{
                            layer.msg("删除失败");
                        }
                    },
                })
            },
        });
    }
</script>
{% endblock %}

templates/article/column/article_post.html
{% extends "article/base.html" %}
{% load staticfiles %}
{% block title %}article column{% endblock %} {% block content %}
<link rel="stylesheet" href="{% static 'editor/css/style.css' %}">
<link rel="stylesheet" href="{% static 'editor/css/editormd.css' %}">

<div style="margin-left:10px">
    <form class="form-horizontal" action="." method="post">{% csrf_token %}
        <div class="row" style="margin-top: 10px;">
            <div class="col-md-2 text-right"><span>标题:</span></div>
            <div class="col-md-10 text-left">{{article_post_form.title}}</div>
        </div>
        <div class="row" style="margin-top: 10px;">
            <div class="col-md-2 text-right"><span>栏目:</span></div>
            <div class="col-md-10 text-left">
                <select id="which_column">
                    {% for column in article_columns %}
                    <option value="{{column.id}}">{{column.column}}</option>
                    {% endfor %}
                </select>
            </div>
        </div>
        <div class="row" style="margin-top: 10px;">
            <div class="col-md-2 text-right"><span>文章标签:</span></div>
            <div class="col-md-10 text-left">
                {% for tag in article_tags %}
                <label class="checkbox-inline">
                    <input class="tagcheckbox-inline" type="checkbox" id="{{ tag.id }}" name="article_tag" value="{{ tag.tag }}">{{ tag.tag }}</input>
                </label>
                {% empty %}
                <p>You have not type tags for articles.Please<a href="{% url 'article:article_tag' %}">input your tags</a></p>
                {% endfor %}
            </div>
        </div>
        <div class="row" style="margin-top: 10px;">
            <div class="col-md-2 text-right"><span>内容:</span></div>
<!--            <div class="col-md-10 text-left">{{article_post_form.body}}</div>-->
            <div id="editormd" class="col-md-10 text-left">
                <textarea style="display:none; " id="id_body"></textarea>
            </div>
        </div>
        <div class="row">
            <input type="button" class="btn btn-primary btn-lg" value="发布" onclick="publish_article()">
        </div>
    </form>
</div>

<script type="text/javascript" src='{% static "js/jquery.js" %}'></script>
<script type="text/javascript" src="{% static 'js/layer.js'%}"></script>
<script type="text/javascript" src="{% static 'js/json2.js' %}"></script>
<script type="text/javascript">
function publish_article(){
    var title = $("#id_title").val();
    var column_id = $("#which_column").val();
    var body = $("#id_body").val();
    var article_tags = [];
    $.each($("input[name='article_tag']:checked"), function(){article_tags.push($(this).val());});
    $.ajax({
        url: "{% url 'article:article_post' %}",
        type: "POST",
        data: {"title":title, "body":body, "column_id":column_id, "tags":JSON.stringify(article_tags)},
        success: function(e){
            if(e=="1"){
                layer.msg("发布成功");
                location.href = "{% url 'article:article_list' %}"; //发布成功，跳转到文章列表页面
            }else if(e=="2"){
                layer.msg("sorry.") ;
            }else{
                layer.msg("项目名称必须写，不能空。");
            }
        },
    });
}
</script>

<script type="text/javascript" src='{% static "editor/editormd.min.js" %}'></script>
<script type="text/javascript">
    $(function() {
        var editor = editormd("editormd", {
            width : "100%",
            height : 640,
            syncScrolling : "single",
            path : "{% static 'editor/lib/' %}"
        });
    });
</script>

{% endblock %}

templates/article/column/redit_article.html
{% extends "article/base.html" %}
{% load staticfiles %}
{% block title %}article column{% endblock %}
{% block content %}
<link rel="stylesheet" href="{% static 'editor/css/style.css' %}">
<link rel="stylesheet" href="{% static 'editor/css/editormd.css' %}">
<div class="container">
<div class="col-md-10">
<div style="margin-left:10px">
    <form class="form-horizontal" action="." method="post">{% csrf_token %}
        <div class="row" style="margin-top: 10px;">
            <div class="col-md-2 text-right"><span>标题:</span></div>
            <div class="col-md-10 text-left">{{this_article_form.title}}</div>
        </div>
        <div class="row" style="margin-top: 10px;">
            <div class="col-md-2 text-right"><span>栏目:</span></div>
            <div class="col-md-10 text-left">
                <select id="which_column">
                    {% for column in article_columns %}
                        {% if column == this_article_column.column %}
                            <option value="{{column.id}}" selected="selected">{{column.column}} </option>
                        {% else %}
                            <option value="{{column.id}}">{{column.column}}</option>

                        {% endif %}
                    {% endfor %}
                </select>
            </div>
        </div>
        <div class="row" style="margin-top: 10px;">
            <div class="col-md-2 text-right"><span>内容:</span></div>
            <div id="editormd" class="col-md-10 text-left">
        <!--{{article_post_form.body}}-->
                <textarea style="display:none;" id="id_body">
{{article.body}}
                </textarea>
            </div>
        </div>
        <div class="row">
            <input type="button" class="btn btn-primary btn-lg" value="发布" onclick="redit_article()">
        </div>
    </form>
</div>
</div>
</div>

<script type="text/javascript" src='{% static "js/jquery.js" %}'></script>
<script type="text/javascript" src='{% static "editor/editormd.min.js" %}'></script>
<script type="text/javascript" src="{% static 'js/layer.js'%}"></script>
<script type="text/javascript">
$(function() {
    var editor = editormd("editormd", {
        width : "100%",
        height : 640,
        //syncScrolling : "single",
        path : "{% static 'editor/lib/' %}",
    });
});

function redit_article(){
    var title = $("#id_title").val();
    var column_id = $("#which_column").val();
    var body = $("#id_body").val();
    $.ajax({
        url: "{% url 'article:redit_article' article.id %}",
        type: "POST",
        data: {"title":title, "body":body, "column_id":column_id},
        success: function(e){
            if(e=="1"){
                layer.msg("编辑成功");
                location.href = "{% url 'article:article_list' %}";
            }else{
                layer.msg("sorry.");
            }
        },
    });
} </script>


</script>
{% endblock %}