account/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_view

app_name="account"

urlpatterns = [
    path('login/',auth_view.LoginView.as_view(template_name='account/login2.html'),name='user_login'), # 这里设置name，为了是在模板文件中，写name就能找到这个路由
    path('logout/',auth_view.LogoutView.as_view(template_name='account/logout.html'),name='user_logout'),
    path('register/',views.register,name='user_register'),
    path('password-change/',auth_view.PasswordChangeView.as_view(template_name="account/password_change_form.html",success_url="/account/password-change-done/"),name='password_change'),
    path('password-change-done/',auth_view.PasswordChangeDoneView.as_view(template_name="account/password_change_done.html"),name='password_change_done'),
    path('password-reset/', auth_view.PasswordResetView.as_view(template_name="account/password_reset_form.html", email_template_name="account/password_reset_email.html", success_url='/account/password-reset-done/'), name='password_reset'),
    path('password-reset-done/', auth_view.PasswordResetDoneView.as_view(template_name="account/password_reset_done.html"), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_view.PasswordResetConfirmView.as_view(template_name="account/password_reset_confirm.html", success_url='/account/password-reset-complete/'), name="password_reset_confirm"),
    path('password-reset-complete/', auth_view.PasswordResetCompleteView.as_view(template_name='account/password_reset_complete.html'), name='password_reset_complete'),
    path('my-information/',views.myself,name="my_information"),
    path('edit-my-information/',views.myself_edit,name="edit_my_information"),
    # path('my-image/',views.my_image,name="my_image"),
]

article/urls.py
from django.urls import path,re_path
from . import views,list_views


app_name = "article"

urlpatterns = [
    path('article-column/',views.article_column,name="article_column"),  # 这里设置name，为了在模板文件中，写name就能找到这个路由
    path('rename-column/', views.rename_article_column, name="rename_article_column"), #编辑文章
    path('del-column/',views.del_article_column,name="del_article_column"), #删除文章
    path('article-post/',views.article_post,name="article_post"), #发布文章
    path('article-list/',views.article_list,name="article_list"), #文章列表
    re_path('article-detail/(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.article_detail, name="article_detail"), #文章详情
    path('del-article/',views.del_article,name="del_article"),
    path('redit-article/<int:article_id>/',views.redit_article,name="redit_article"),
    path('list-article-titles/',list_views.article_titles,name="article_titles"),
    path('article-content/<int:id>/<slug:slug>/',list_views.article_detail,name="article_content"), #此处也是显示文章详情，对应不同的html模板
    path('list-article-titles/<username>/',list_views.article_titles,name="author_articles"),
    path('like-article/',list_views.like_article,name="like_article"),
    path('article-tag/',views.article_tag,name="article_tag"),
    path('del-article-tag/',views.del_article_tag,name="del_article_tag"),
]

blog/urls.py
from django.urls import path
from . import views

app_name = "blog"

urlpatterns = [
    path('',views.blog_title,name='blog_title'),  #name是别名
    path('<int:article_id>/',views.blog_article,name='blog_article'), #views.blog_article也可以加上"",用"views.blog_article"显示
]

course/urls.py
from django.urls import path
from django.views.generic import TemplateView
from .views import CourseListView,ManageCourseListView,CreateCourseView,DeleteCourseView,CreateLessonView,ListLessonView,DetailLessonView,StudentListLessonView,UpdateCourseView


app_name = "course"

urlpatterns = [
    path('about/',TemplateView.as_view(template_name="course/about.html"),name="about"), #关于本站
    path('course-list/',CourseListView.as_view(),name="course_list"), #课程列表
    path('manage-course/',ManageCourseListView.as_view(),name="manage_course"),
    path('create-course/',CreateCourseView.as_view(),name="create_course"),
    path('update-course/<int:pk>/',UpdateCourseView.as_view(),name="update_course"),
    path('delete-course/<int:pk>/',DeleteCourseView.as_view(),name="delete_course"),
    path('create-lesson/',CreateLessonView.as_view(),name="create_lesson"),
    path('list-lessons/<int:course_id>/',ListLessonView.as_view(),name="list_lessons"),
    path('detail-lessons/<int:lesson_id>/',DetailLessonView.as_view(),name="detail_lesson"),
    path('lessons-list/<int:course_id>/',StudentListLessonView.as_view(),name="lessons_list"),
]

image/urls.py
from django.urls import path
from . import views

app_name = 'image'

urlpatterns = [
    path('list-images/', views.list_images, name="list_images"),
    path('upload-image/', views.upload_image, name='upload_image'),
    path('del-image/',views.del_image,name="del_image"),
    path('images/',views.falls_images,name="falls_images"), #瀑布流展示图片
    ]

mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('blog/',include('blog.urls','blog'),namespace='blog'),
    path('blog/',include('blog.urls',namespace='blog')),
    path('account/',include('account.urls',namespace = 'account')),
    path('article/',include('article.urls',namespace = 'article')),
    path('home/', TemplateView.as_view(template_name="home.html"), name='home'), # 这里设置name，为了在模板文件中，写name就能找到这个路由，name参数相当于别名
    path('image/',include('image.urls',namespace = 'image')),
    path('course/',include('course.urls',namespace='course')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load staticfiles %}
<! DOCTYPE html>
<html lang="zh-cn">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
</head>
    <body>
        {% include "header.html" %}
        <div class="container">
            {% block content %}
            {% endblock %}
        </div>
        {% include "footer.html" %}
        {% block javascript %}
        {% endblock %}
    </body>
</html>

templates/footer.html
<div class="container">
    <br>
    <br>
    <br>
    <br>
    <br>
    <p class="text-center">服务热线：400-811-XXXX 周一至周日 9:00-22:00</p>
    <p class="text-center">联系地址：深圳市南山区南山街道南油大厦B栋1203室</p>
    <p class="text-center">Copyright 2020 雨墨科技有限公司 All Rights Reserved. 粤ICP备XX0942XX号-1</p>
</div>

templates/header.html
{% load staticfiles %}
<div class="container">
    <nav class="navbar navbar-default" role="navigation">
        <div class="navbar-header">
            <a class="navbar-brand" href="http://www.itdiffer.com">
                <img src="{% static '/images/homelogo.png' %}" width="100px">
            </a>
        </div>
        <div>
            <ul class="nav navbar-nav" role="navigation">
                <li><a href="{% url 'home' %}">Home|主页</a></li>
                <li><a href="{% url 'blog:blog_title' %}">博客</a></li>
<!--                url是Django模板内置的标记符，表示此处返回由应用跟参数组成的URL，其中blog:blog_title中，blog是应用名称，blog_title是应用中URL的名称，相当于别名-->
                <li><a href="{% url 'article:article_titles' %}">文章</a></li>
                <li><a href="{% url 'course:course_list' %}">课程</a></li>
                <li><a href="{% url 'image:falls_images' %}">美图</a></li>
                <li><a href="{% url 'course:about' %}">关于本站</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right" style="margin-right:10px">
                {% if user.is_authenticated %}
                <li>
                    <div class="dropdown" style="margin-top:8px">
                        <button class='btn btn-default dropdown-toggle' type='button' id='dropdownMenu' data-toggle='dropdown'>{{ user.username }}
                            <span class='caret'></span>
                        </button>
                        <ul class="dropdown-menu">
                            <li><a href="{% url 'account:password_change' %}">修改密码</a></li>
                            <li><a href="{% url 'account:my_information' %}">个人信息</a></li>
                            <li><a href="{% url 'article:article_column' %}">后台管理</a></li>
                        </ul>
                    </div>
                </li>
                <li><a href="{% url 'account:user_logout' %}">登出</a></li>
                {% else %}
                <li><a href="{% url 'home' %}">Home|主页</a></li>
                <li><a href="{% url 'account:user_login' %}">登录</a></li>
                <li><a href="{% url 'account:user_register' %}">注册</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>
</div>

<script src="{% static 'js/jquery.js' %}"></script>
<script src="{% static 'js/bootstrap.js' %}"></script>

templates/home.html
{% extends "base.html" %}
{% block title %}Home Page{% endblock %}
{% block content %}
<div class="text-center">
    <h1>Welcome You</h1>
    <h3>Life is short. You need Python</h3>

    <h2>Django makes it easier to build better Web apps more quickly and with less code.</h2>
    {% load staticfiles %}
    <img src="{% static 'images/5Glogo.jpg' %}">
</div>
{% endblock %}

templates/paginator.html
<!--<div class="pagination">-->
<!--    <span class="step-links">-->
<!--        {% if page.has_previous %}-->
<!--        <a href="?page={{page.previous_page_number}}">Previous</a>-->
<!--        {% endif %}-->
<!--        <span class="current">-->
<!--            Page {{ page.number }} of {{ page.paginator.num_pages }}-->
<!--        </span>-->
<!--        {% if page.has_next %}-->
<!--        <a href="?page={{ page.next_page_number }}" >Next</a>-->
<!--        {% endif %}-->
<!--    </span>-->
<!--</div>-->
<div class="pagination">
    <span class="step-links">
        {% if page.has_previous %}
        <a href="?page={{ page.previous_page_number }}">Previous</a>
        {% endif %}
        <span class="current">
            Page {{ page.number }} of {{ page.paginator.num_pages }}
        </span>
        {% if page.has_next %}
        <a href="?page={{ page.next_page_number }}">Next</a> {% endif %}
    </span>
</div>